runtime: nodejs18
service: api
instance_class: B8
basic_scaling:
  max_instances: 25
  idle_timeout: 15m

vpc_access_connector:
  name: projects/papertrading-378100/locations/us-west1/connectors/mongoatlas
  egress_setting: all-traffic